"""Step 3: pruning, INT8 quantization and TFLite conversion (slide 13 pipeline).

Why tf_keras: Keras 3 compiles LSTMs to TensorList loops that the TFLite converter cannot lower to
built-in ops (verified: conversion fails), and unrolling the loop instead bloats the model to
several hundred KB. Legacy Keras 2 (tf_keras) LSTMs convert to TFLite's fused
UNIDIRECTIONAL_SEQUENCE_LSTM, which is compact and has an INT8 kernel in TFLite Micro.
The weights are identical, so the trained Keras 3 model is copied across exactly.
"""
import gzip
import os
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")
import numpy as np
import keras
import tensorflow as tf
import tf_keras
from tf_keras import layers as L


# ---- pruning ---------------------------------------------------------------------------------
def prunable(model):
    """Weight matrices and kernels (rank >= 2). Biases are left alone."""
    return [v for v in model.trainable_weights if len(v.shape) >= 2]


def make_masks(model, sparsity=0.35):
    """Per-tensor magnitude pruning: the smallest `sparsity` fraction of each tensor is zeroed."""
    pairs = []
    for v in prunable(model):
        w = v.numpy()
        m = (np.abs(w) > np.quantile(np.abs(w), sparsity)).astype(w.dtype)
        v.assign(w * m)
        pairs.append((v, m))
    return pairs


class KeepMasks(keras.callbacks.Callback):
    """Re-zero pruned weights after every optimizer step so fine-tuning cannot revive them."""
    def __init__(self, pairs):
        super().__init__()
        self.pairs = pairs

    def on_train_batch_end(self, batch, logs=None):
        for v, m in self.pairs:
            v.assign(v.numpy() * m)


def sparsity_of(model):
    z = sum(int((v.numpy() == 0).sum()) for v in prunable(model))
    n = sum(v.numpy().size for v in prunable(model))
    return z / n


# ---- Keras 3 -> tf_keras -> TFLite ------------------------------------------------------------
def to_tf_keras(model3, lstm_units=32):
    """Rebuild deep.cnn_bilstm with legacy layers, batch size 1 (as on the device), same weights."""
    inp = tf_keras.Input((50, 6), batch_size=1)
    x = L.Conv1D(16, 5, padding="same", activation="relu")(inp)
    x = L.Conv1D(32, 3, padding="same", activation="relu")(x)
    x = L.Bidirectional(L.LSTM(lstm_units))(x)
    x = L.Dense(32, activation="relu")(x)
    x = L.Dropout(0.3)(x)
    m = tf_keras.Model(inp, L.Dense(2, activation="softmax")(x))
    m.set_weights(model3.get_weights())
    return m


def convert(tfk_model, mode="int8", rep_X=None):
    """mode: 'float32' | 'dynamic' | 'int8' (full integer, int8 in and out, needs rep_X)."""
    c = tf.lite.TFLiteConverter.from_keras_model(tfk_model)
    if mode != "float32":
        c.optimizations = [tf.lite.Optimize.DEFAULT]
    if mode == "int8":
        c.representative_dataset = lambda: ([r[None].astype(np.float32)] for r in rep_X)
        c.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        c.inference_input_type = tf.int8
        c.inference_output_type = tf.int8
    return c.convert()


class TFLiteRunner:
    """Runs a .tflite model one window at a time, quantizing input and dequantizing output the way
    the firmware will."""
    def __init__(self, blob):
        # reference kernels only (no XNNPACK delegate): closest to what TFLite Micro executes
        self.it = tf.lite.Interpreter(
            model_content=blob,
            experimental_op_resolver_type=tf.lite.experimental.OpResolverType.BUILTIN_WITHOUT_DEFAULT_DELEGATES)
        self.it.allocate_tensors()
        self.i, self.o = self.it.get_input_details()[0], self.it.get_output_details()[0]

    def ops(self):
        return sorted({d["op_name"] for d in self.it._get_ops_details()})

    def predict_proba(self, X):
        out = np.empty((len(X), 2), np.float32)
        qi, qo = self.i["quantization"], self.o["quantization"]
        for k, x in enumerate(X):
            x = x[None].astype(np.float32)
            if self.i["dtype"] == np.int8:
                x = np.clip(np.round(x / qi[0]) + qi[1], -128, 127).astype(np.int8)
            self.it.set_tensor(self.i["index"], x)
            self.it.invoke()
            y = self.it.get_tensor(self.o["index"])
            out[k] = (y.astype(np.float32) - qo[1]) * qo[0] if self.o["dtype"] == np.int8 else y
        return out

    def predict(self, X, thr=0.5):
        return (self.predict_proba(X)[:, 1] > thr).astype(int)


def gzip_kb(blob):
    return len(gzip.compress(blob, 9)) / 1024


def to_c_array(blob, name="g_prefall_model"):
    """C source for the firmware (TFLite Micro loads the model from a const byte array)."""
    rows = [", ".join(f"0x{b:02x}" for b in blob[i:i + 12]) for i in range(0, len(blob), 12)]
    body = ",\n  ".join(rows)
    return (f"// generated by prefall/deploy.py, {len(blob)} bytes\n"
            f"alignas(16) const unsigned char {name}[] = {{\n  {body}\n}};\n"
            f"const unsigned int {name}_len = {len(blob)};\n")
