// OPTIONAL, UNTESTED: INT8 CNN-BiLSTM classifier on TensorFlow Lite Micro (needed for detector B).
// Detector A (threshold + SVM) does NOT need this file: the SVM is plain C++ in core/svm.h.
//
// Build with -DPREFALL_USE_TFLM after adding a TFLite Micro library for ESP32 (for example the
// esp-tflite-micro component under ESP-IDF, or a maintained Arduino port) and -I../../export.
// The op list below is exactly what run_step3.py printed for the exported model, and all eight are
// registered in TFLite Micro's MicroMutableOpResolver.
#pragma once
#ifdef PREFALL_USE_TFLM
#include <cmath>
#include <cstdint>
#include <tensorflow/lite/micro/micro_interpreter.h>
#include <tensorflow/lite/micro/micro_mutable_op_resolver.h>
#include <tensorflow/lite/schema/schema_generated.h>
#include "cnn_bilstm_int8_model.h"   // g_prefall_model[], generated by run_step3.py
#include "prefall_config.h"

class TflmClassifier {
 public:
  float last_prob = 0.f;

  bool begin() {
    const tflite::Model* model = tflite::GetModel(g_prefall_model);
    resolver_.AddConcatenation();
    resolver_.AddConv2D();
    resolver_.AddFullyConnected();
    resolver_.AddReshape();
    resolver_.AddReverseV2();
    resolver_.AddSoftmax();
    resolver_.AddStridedSlice();
    resolver_.AddUnidirectionalSequenceLSTM();
    interp_ = new tflite::MicroInterpreter(model, resolver_, arena_, kArena);
    if (interp_->AllocateTensors() != kTfLiteOk) return false;
    arenaUsed_ = interp_->arena_used_bytes();   // log this, then shrink kArena to fit
    return true;
  }
  size_t arenaUsed() const { return arenaUsed_; }

  static bool classify(void* ctx, const float* window) {
    auto* self = static_cast<TflmClassifier*>(ctx);
    static const float kScale[prefall::kCh] = {4.f, 4.f, 4.f, 250.f, 250.f, 250.f};   // same as dataset.SCALE
    TfLiteTensor* in = self->interp_->input(0);
    const float s = in->params.scale;
    const int zp = in->params.zero_point;
    for (int n = 0; n < prefall::kWin; ++n)
      for (int c = 0; c < prefall::kCh; ++c) {
        int q = static_cast<int>(std::lround(window[n * prefall::kCh + c] / kScale[c] / s)) + zp;
        in->data.int8[n * prefall::kCh + c] = static_cast<int8_t>(q < -128 ? -128 : (q > 127 ? 127 : q));
      }
    if (self->interp_->Invoke() != kTfLiteOk) return false;
    TfLiteTensor* out = self->interp_->output(0);
    self->last_prob = (out->data.int8[1] - out->params.zero_point) * out->params.scale;
    return self->last_prob > 0.5f;
  }

 private:
  static constexpr size_t kArena = 64 * 1024;   // starting guess; tune from arenaUsed()
  alignas(16) uint8_t arena_[kArena];
  tflite::MicroMutableOpResolver<8> resolver_;
  tflite::MicroInterpreter* interp_ = nullptr;
  size_t arenaUsed_ = 0;
};
#endif  // PREFALL_USE_TFLM
