"""Export everything the C++ firmware core needs from the trained Python pipeline.

    python tools/export_firmware_assets.py     (needs scripts/run_step1.py first)

Writes:
  firmware/core/generated/lpf_coeffs.h        Butterworth biquad coefficients (slide 9)
  firmware/core/generated/threshold_params.h  calibrated first-pass threshold (slide 14)
  firmware/core/generated/svm_model.h         scaler + RBF SVM (confirmer for detector A)
  firmware/test/vectors.bin                   raw sensor streams + the Python results the C++ must match
"""
import os
import pickle
import struct
import sys

import numpy as np
from scipy import signal

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
sys.path.insert(0, ROOT)
os.chdir(ROOT)
from prefall.classical import make_models
from prefall.config import FS, FS_RAW, LPF_HZ
from prefall.dsp import condition
from prefall.evaluate import calibrate
from prefall.features import sliding_windows, window_features
from prefall.hybrid import confirmed_alarms
from prefall.threshold import trace, alarm_mask
from prefall.alert import pack_alert

OUT = "firmware/core/generated"
os.makedirs(OUT, exist_ok=True)


def arr(name, a, per_line=6):
    a = np.asarray(a).ravel()
    rows = [", ".join(f"{v:.9e}f" for v in a[i:i + per_line]) for i in range(0, len(a), per_line)]
    return f"constexpr float {name}[{len(a)}] = {{\n    " + ",\n    ".join(rows) + "\n};\n"


trials = pickle.load(open("data/step1_trials.pkl", "rb"))
half = len(trials) // 2
train_tr, test_tr = trials[:half], trials[half:]

# 1. low-pass biquad
b, a = signal.butter(2, LPF_HZ / (FS_RAW / 2.0), btype="low")
with open(f"{OUT}/lpf_coeffs.h", "w") as f:
    f.write("// generated by tools/export_firmware_assets.py: do not edit\n#pragma once\nnamespace prefall {\n")
    f.write(f"// 2nd-order Butterworth low-pass, fc = {LPF_HZ} Hz at fs = {FS_RAW} Hz\n")
    f.write(arr("kLpfB", b) + arr("kLpfA", a) + "}  // namespace prefall\n")

# 2. threshold parameters (calibrated on training trials only, as in steps 1-4)
p = calibrate(train_tr, [trace(condition(t.raw)) for t in train_tr], mode="first_pass")
with open(f"{OUT}/threshold_params.h", "w") as f:
    f.write("// generated by tools/export_firmware_assets.py: do not edit\n#pragma once\nnamespace prefall {\n")
    f.write(f"constexpr float kThetaCritDeg = {float(p.theta_crit):.6f}f;\nconstexpr float kVThrMps = {float(p.v_thr):.6f}f;\n"
            f"constexpr float kTau = {float(p.tau):.6f}f;\n}}  // namespace prefall\n")

# 3. SVM confirmer
d = np.load("data/step1_windows.npz")
svm = make_models()["SVM (RBF)"].fit(d["X"][d["train_mask"]], d["y"][d["train_mask"]])
sc, clf = svm[0], svm[-1]
nsv = clf.support_vectors_.shape[0]
with open(f"{OUT}/svm_model.h", "w") as f:
    f.write("// generated by tools/export_firmware_assets.py: do not edit\n#pragma once\nnamespace prefall {\n")
    f.write(f"constexpr int kSvmNsv = {nsv};\nconstexpr float kSvmGamma = {clf._gamma:.9e}f;\n"
            f"constexpr float kSvmB = {float(clf.intercept_[0]):.9e}f;\n")
    f.write(arr("kSvmMean", sc.mean_) + arr("kSvmScale", sc.scale_) + arr("kSvmCoef", clf.dual_coef_[0]))
    f.write(arr("kSvmSv", clf.support_vectors_, per_line=12) + "}  // namespace prefall\n")
print(f"svm: {nsv} support vectors, gamma {clf._gamma:.4f}; threshold: {p}")

# 4. test vectors: 2 trials of each kind from the held-out set
kinds = ["walk", "stairs", "sit_fast", "jump", "stumble", "fall"]
picked = [t for k in kinds for t in [x for x in test_tr if x.kind == k][:2]]
POLICIES = [(0, 0, "A"), (100, 100, "A"), (300, 300, "B")]      # (delay ms, persist ms, trigger source)
buf = bytearray(struct.pack("<i", len(picked)))
for tr in picked:
    x = condition(tr.raw)
    n50 = len(x)
    th, vd = trace(x)
    mask = alarm_mask(th, vd, p)
    W, _ = sliding_windows(x, 50, 1)
    feats = np.stack([window_features(w) for w in W])
    dec = np.full(n50, np.nan)
    dec[49:] = svm.decision_function(feats)
    pred = np.zeros(n50, bool)
    pred[49:] = dec[49:] > 0
    buf += struct.pack("<ii", len(tr.raw), n50)
    buf += tr.raw.astype("<f4").tobytes() + x.astype("<f4").tobytes()
    buf += th.astype("<f4").tobytes() + vd.astype("<f4").tobytes() + mask.astype("u1").tobytes()
    buf += dec.astype("<f4").tobytes() + feats.astype("<f4").tobytes()
    for dly, per, src in POLICIES:
        al = confirmed_alarms(mask if src == "A" else pred, pred, dly, per)
        buf += struct.pack("<iiii", dly, per, 0 if src == "A" else 1, len(al))
        for s in al:
            buf += struct.pack("<i", s) + pack_alert(s * 1000 // FS, 0x0A01, 0.5, 0 if src == "A" else 1)
open("firmware/test/vectors.bin", "wb").write(buf)
print(f"wrote {len(picked)} test trials ({len(buf)/1024:.0f} KB) to firmware/test/vectors.bin")
